package com.example.gnss_app.ble.contance
object ProtocolID {
    val SERVICE_HEART: UShort = 0u
    val APP_INFO: UShort = 256u
    val SERVICE_R_WKMODE: UShort = 0u
    val SERVICE_W_WKMODE: UShort = 0u
    val SERVICE_R_NETMOD: UShort = 0u
    val SERVICE_W_NETMOD: UShort = 0u
    val SERVICE_R_IPMOD: UShort = 0u
    val SERVICE_W_IPMOD: UShort = 0u
    val SERVICE_R_DBGMOD: UShort = 0u
    val SERVICE_W_DBGMOD: UShort = 0u
    val SERVICE_R_TEL: UShort = 0u
    val SERVICE_W_TEL: UShort = 0u
    val SERVICE_R_UART: UShort = 0u
    val SERVICE_W_UART: UShort = 0u
    val SERVICE_R_SYSPWD: UShort = 0u
    val SERVICE_W_SYSPWD: UShort = 0u
    val SERVICE_R_TOKEN: UShort = 0u
    val SERVICE_W_TOKEN: UShort = 0u
    val SERVICE_R_GPRS_STATE: UShort = 0u
    val SERVICE_W_GPRS_STATE: UShort = 0u
    val SERVICE_R_SERVER_IP: UShort = 0u
    val SERVICE_W_SERVER_IP: UShort = 0u
    val SERVICE_R_NTRIP_IP: UShort = 0u
    val SERVICE_W_NTRIP_IP: UShort = 0u
    val SERVICE_R_GNSS_NTRIP_MOUNT: UShort = 0u
    val SERVICE_W_GNSS_NTRIP_MOUNT: UShort = 0u
    val SERVICE_R_GNSS_NTRIP_ACCONT: UShort = 0u
    val SERVICE_W_GNSS_NTRIP_ACCONT: UShort = 0u
    val SERVICE_R_GNSS_NTRIP_PASSWD: UShort = 0u
    val SERVICE_W_GNSS_NTRIP_PASSWD: UShort = 0u
    val SERVICE_R_HBTIME: UShort = 0u
    val SERVICE_W_HBTIME: UShort = 0u

    // valSERVICE_R_APN
// :UShort = 0uvalSERVICE_W_APN
// :UShort = 0uvalSERVICE_R_IDLTIME
// :UShort = 0uvalSERVICE_W_IDLTIME
    val SERVICE_SAVE_CONFIG: UShort = 0u
    val SERVICE_GPRS: UShort = 0u
    val SERVICE_GPRS_CACHE: UShort = 0u
    val SERVICE_GNSS_NTRIP: UShort = 0u
    val SERVICE_ID: UShort = 0u
    val SERVICE_DCDAID: UShort = 0u
    val SERVICE_CSQ: UShort = 0u
    val SERVICE_GSTCDE: UShort = 0u
    val SERVICE_IP: UShort = 0u
    val SERVICE_REG: UShort = 0u
    val SERVICE_ICCID: UShort = 0u
    val SERVICE_IMEI: UShort = 0u
    val SERVICE_RESTART: UShort = 0u
    val SERVICE_FILE: UShort = 0u
    val SERVICE_FILE_COMD: UShort = 0u
    val SERVICE_GPIO: UShort = 0u
    val SERVICE_ADC: UShort = 0u
    val SERVICE_BT: UShort = 0u
    val SERVICE_CDA: UShort = 0u
    val SERVICE_SD: UShort = 0u
    val SERVICE_OPERATE_RESPONSE: UShort = 0u
    val SERVICE_SOCKET_SWITCH: UShort = 0u
    val SERVICE_SOCKET_DISCONNECT: UShort = 0u
    val SERVICE_CHECK_UPDATE: UShort = 0u
    val SERVICE_UPDATE: UShort = 0u
    val SERVICE_DEBUG_UART_OUT_ENABLE: UShort = 0u
    val SERVICE_READ_CONFIG: UShort = 0u
    val SERVICE_CLEAN_CONFIG: UShort = 0u
    val SERVICE_GPRS_MSG: UShort = 0u
}