package com.example.gnss_app.ble.contance
object ProtocolID {
    const val SERVICE_HEART: UShort = 0u
    val APP_INFO: UShort = 1u
    val SERVICE_R_WKMODE: UShort = 2u
    val SERVICE_W_WKMODE: UShort = 3u
    val SERVICE_R_NETMOD: UShort = 4u
    val SERVICE_W_NETMOD: UShort = 5u
    val SERVICE_R_IPMOD: UShort = 6u
    val SERVICE_W_IPMOD: UShort = 7u
    val SERVICE_R_DBGMOD: UShort = 8u
    val SERVICE_W_DBGMOD: UShort = 9u
    val SERVICE_R_TEL: UShort = 10u
    val SERVICE_W_TEL: UShort = 11u
    val SERVICE_R_UART: UShort = 12u
    val SERVICE_W_UART: UShort = 13u
    val SERVICE_R_SYSPWD: UShort = 0u
    val SERVICE_W_SYSPWD: UShort = 0u
    val SERVICE_R_TOKEN: UShort = 0u
    val SERVICE_W_TOKEN: UShort = 0u
    val SERVICE_R_GNSS_STATE: UShort = 18u
    val SERVICE_W_GNSS_STATE: UShort = 19u
    val SERVICE_R_SERVER_IP: UShort = 20u
    val SERVICE_W_SERVER_IP: UShort = 21u

    val SERVICE_R_NTRIP_IP: UShort = 22u
    val SERVICE_W_NTRIP_IP: UShort = 23u
    val SERVICE_R_NTRIP_MOUNT: UShort = 24u
    val SERVICE_W_NTRIP_MOUNT: UShort = 25u
    val SERVICE_R_NTRIP_ACCONT: UShort = 26u
    val SERVICE_W_NTRIP_ACCONT: UShort = 27u
    val SERVICE_R_NTRIP_PASSWD: UShort = 28u
    val SERVICE_W_NTRIP_PASSWD: UShort = 29u
    val SERVICE_R_HBTIME: UShort = 0u
    val SERVICE_W_HBTIME: UShort = 0u

    // valSERVICE_R_APN
// :UShort = 0uvalSERVICE_W_APN
// :UShort = 0uvalSERVICE_R_IDLTIME
// :UShort = 0uvalSERVICE_W_IDLTIME
    val SERVICE_SAVE_CONFIG: UShort = 0u
    val SERVICE_GNSS: UShort = 0u
    val SERVICE_GNSS_CACHE: UShort = 0u
    val SERVICE_NTRIP_SWITCH: UShort = 35u
    val SERVICE_ID: UShort = 0u
    val SERVICE_DCDAID: UShort = 0u
    val SERVICE_CSQ: UShort = 0u
    val SERVICE_GSTCDE: UShort = 0u
    val SERVICE_IP: UShort = 0u
    val SERVICE_REG: UShort = 0u
    val SERVICE_ICCID: UShort = 0u
    val SERVICE_IMEI: UShort = 0u
    val SERVICE_RESTART: UShort = 0u
    val SERVICE_FILE: UShort = 0u
    val SERVICE_FILE_COMD: UShort = 0u
    val SERVICE_GPIO: UShort = 0u
    val SERVICE_ADC: UShort = 0u
    val SERVICE_BT: UShort = 0u
    val SERVICE_CDA: UShort = 0u
    val SERVICE_SD: UShort = 0u
    val SERVICE_OPERATE_RESPONSE: UShort = 0u
    val SERVICE_SOCKET_SWITCH: UShort = 53u
    val SERVICE_SOCKET_DISCONNECT: UShort = 0u
    val SERVICE_CHECK_UPDATE: UShort = 0u
    val SERVICE_UPDATE: UShort = 0u
    val SERVICE_DEBUG_UART_OUT_ENABLE: UShort = 0u
    val SERVICE_READ_CONFIG: UShort = 0x3a00u
    val SERVICE_CLEAN_CONFIG: UShort = 0u
    val SERVICE_GNSS_MSG: UShort = 0u
}