package com.example.gnss_app.ble.repository

enum class EventType {
    ON_NULL,
    ON_R_APP_INFO,
    ON_R_CONFIG,

    ON_R_WKMODE_CONFIG,
    ON_W_WKMODE_CONFIG,
    ON_R_NETMOD_CONFIG, ON_W_NETMOD_CONFIG,
    ON_R_IPMOD_CONFIG, ON_W_IPMOD_CONFIG,
    ON_R_DBGMOD_CONFIG, ON_W_DBGMOD_CONFIG,
    ON_R_TEL_CONFIG, ON_W_TEL_CONFIG,
    ON_R_UART_CONFIG, ON_W_UART_CONFIG,
    ON_R_SYSPWD_CONFIG, ON_W_SYSPWD_CONFIG, ON_R_TOKEN_CONFIG,
    ON_W_TOKEN_CONFIG,
    ON_R_GNSS_STATE_CONFIG,
    ON_W_GNSS_STATE_CONFIG, ON_R_SERVER_IP_CONFIG,
    ON_W_SERVER_IP_CONFIG, ON_R_NTRIP_IP_CONFIG, ON_W_NTRIP_IP_CONFIG,
    ON_R_NTRIP_MOUNT_CONFIG, ON_W_NTRIP_MOUNT_CONFIG,
    ON_R_NTRIP_ACCONT_CONFIG, ON_W_NTRIP_ACCONT_CONFIG,
    ON_R_NTRIP_PASSWD_CONFIG, ON_W_NTRIP_PASSWD_CONFIG,
    ON_R_HBTIME_CONFIG, ON_W_HBTIME_CONFIG,


    ON_NTRIP_SWITCH,


    ON_SAVE_CONFIG
    , ON_GPRS
    , ON_GPRS_CACHE
    , ON_GNSS_NTRIP
    , ON_ID
    , ON_DCDAID
    , ON_CSQ
    , ON_GSTCDE
    , ON_IP
    , ON_REG
    , ON_ICCID
    , ON_IMEI
    , ON_RESTART
    , ON_FILE
    , ON_FILE_COMD
    , ON_GPIO
    , ON_ADC

    , ON_BT_SWITCH
    , ON_CDA
    , ON_SD
    , ON_OPERATE_RESPONSE
    , ON_SOCKET_SWITCH
    , ON_SOCKET_DISCONNECT
    , ON_CHECK_UPDATE
    , ON_UPDATE
    , ON_DEBUG_UART_OUT_ENABLE
    , ON_READ_CONFIG
    , ON_CLEAN_CONFIG
    , ON_GPRS_MSG
}