package com.example.gnss_app.ble.repository

enum class EventType {
    ON_NULL,
    ON_WIFI_SCAN_RESULT,
    ON_R_APP_INFO,
    ON_R_CONFIG,
    ON_R_SERVER_CONFIG,
    ON_W_SERVER_CONFIG,

    ON_R_WKMODE_CONFIG,
    ON_W_WKMODE_CONFIG,
    ON_R_NETMOD_CONFIG, ON_W_NETMOD_CONFIG, ON_R_IPMOD_CONFIG, ON_W_IPMOD_CONFIG, ON_R_DBGMOD_CONFIG, ON_W_DBGMOD_CONFIG, ON_R_TEL_CONFIG, ON_W_TEL_CONFIG, ON_R_UART_CONFIG, ON_W_UART_CONFIG, ON_R_SYSPWD_CONFIG, ON_W_SYSPWD_CONFIG, ON_R_TOKEN_CONFIG, ON_W_TOKEN_CONFIG,
    ON_R_GNSS_STATE_CONFIG,
    ON_W_GNSS_STATE_CONFIG, ON_R_SERVER_IP_CONFIG,
    ON_W_SERVER_IP_CONFIG, ON_R_NTRIP_IP_CONFIG, ON_W_NTRIP_IP_CONFIG, ON_R_GNSS_NTRIP_MOUNT_CONFIG, ON_W_GNSS_NTRIP_MOUNT_CONFIG, ON_R_GNSS_NTRIP_ACCONT_CONFIG, ON_W_GNSS_NTRIP_ACCONT_CONFIG, ON_R_GNSS_NTRIP_PASSWD_CONFIG, ON_W_GNSS_NTRIP_PASSWD_CONFIG, ON_R_HBTIME_CONFIG, ON_W_HBTIME,
}